
services:

  postgres:
    image: postgres:16
    container_name: echocart-postgres
    restart: always
    environment:
      POSTGRES_DB: echocart
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: tempPassword
    ports:
      - "5432:5432"
    networks:
      - echocart-network

  backend:
    build: .
    container_name: echocart-backend
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    depends_on:
      - postgres
    networks:
      - echocart-network

networks:
  echocart-network:
    driver: bridge