spring.application.name=EchoCart

spring.datasource.url= jdbc:postgresql://localhost:5432/echocart
spring.datasource.username=postgres
spring.datasource.password=srijanbanegapostgresql
#spring.jpa.hibernate.ddl-auto=create

jwt.custom.password=srijanisagreatboyimeanamannotspidermanthoughanywaysithinkthispasslongenough



